name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ] #    will run on pull request

jobs:
  simple_deployment_pipeline: # set up environment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2  # runs a specific action - public action (checks out project source code from git)
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        if: ${{ github.event_name == 'push' }}  # runs only on push to master or pull_request merge with master
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: "pokedex-zim"
          heroku_email: "vadzimkk@gmail.com"
          healthcheck: "https://pokedex-zim.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

