name: Deployment pipeline

on:
  push:
    branches:
      - main # TODO change to master
  pull_request:
    branches: [ main ]  # TODO change to master
    types: [ opened, synchronize ] #    will run on pull request

jobs:
  simple_deployment_pipeline: # set up environment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2  # runs a specific action - public action (checks out project source code from git)
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}  # runs only on push to master or pull_request merge with master, skips when message contains #skip
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: "pokedex-zim"
          heroku_email: "vadzimkk@gmail.com"
          healthcheck: "https://pokedex-zim.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
#      - uses: actions/checkout@v2  # this is here to fix "tag not created properly"
#      - name: bump version and push tag
#        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}  # runs only on push to master or pull_request merge with master, skips when message contains #skip
#        uses: anothrNick/github-tag-action@1.33.0
#        env:
#          GIHUB_TOKEN: ${{secrets.BUMP_VERSION}}  # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
#          DEFAULT_BUMP: patch
  - name: notify onSuccess
      if: ${{ github.event_name == 'push' && success() }} # Pick up events even if the job fails or is canceled.
      uses: 8398a7/action-slack@v3  # slack notification
      with:
        status: custom  #------
        fields: commit, author, took
        custom_payload: |
          {
          attachments: [{
          color: 'good',
          text: `a new version deployed to https://pokedex-zim.herokuapp.com/ (${process.env.AS_COMMIT})by ${process.env.AS_AUTHOR}\nbuild took ${process.env.AS_TOOK}`
          }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      - name: notify onFailure
        if: ${{ github.event_name == 'push' && !success() }} # Pick up events even if the job fails or is canceled.
        uses: 8398a7/action-slack@v3  # slack notification
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required


